### ISSUE TITLE
我的rexxar-web的example跑不起来

### ISSUE THREAD

**Issue by sayyanfu** [douban/rexxar-web#17]
git拉去rexxar-web后执行
rexxar-web\example>npm i
rexxar-web\example>gulp serve
后报错
ERROR in ../lib/rexxarFetch.js
Module not found: Error: Cannot resolve module 'isomorphic-fetch' in C:\Users\Hello\Downloads\Rexxar\rexxar-web\lib
 @ ../lib/rexxarFetch.js 8:23-50
webpack: Failed to compile.
打开后看到文件rexxarFetch.js
第8行是var _isomorphicFetch = require('isomorphic-fetch');
require的isomorphic-fetch找不到
然后我执行>npm install --save isomorphic-fetch es6-promise
+ es6-promise@3.3.1
+ isomorphic-fetch@2.2.1
再执行>gulp serve 还是报相同的错。

**Comment by ianwith** [comment]
fixed https://github.com/douban/rexxar-web/pull/18
