### ISSUE TITLE
rexxar-web 和 iOS Android 必须配合使用吗？

### ISSUE THREAD

**Issue by simcyber** [douban/rexxar-web#6]
rexxar-iOS & Android  的页面必须由 rexxar-web  生成调用，还是可以使用其他web服务器的页面？
谢谢！

**Comment by guoshao-dev** [comment]
页面渲染使用其他脚本语言应该也可以。但这样部分业务逻辑就是在后端由 jsp，php 这样的脚本语言完成。然后，生成 html，再下载到 WebView 运行。

这种用法和我们设计初衷相差挺大的。Rexxar 设计为 Rexxar-Web 端只能是运行于浏览器中的 JavaScript 完成业务逻辑，并借助 HTML，CSS 实现 UI 界面。整个过程，服务端不应参与客户端的业务逻辑，而只是提供一个 html 资源的下载服务。这时，服务端可以，也应该只是一个静态资源站点。这种设计下，动态脚本语言其实作用不大。但也并不排斥，只是没有必要而已。
