### ISSUE TITLE
有配套的热更新解决方案吗？

### ISSUE THREAD

**Issue by EllaZhao** [douban/rexxar-web#7]
rexxar-web 的热更新是怎么做的？ 完全自己实现的还是使用了类似CodePush的中央仓库完成发布更新的？

**Comment by baihuayao** [comment]
现在只知道有插件可以用，成熟的一套还不懂。 发自网易邮箱大师 在2017年02月21日 15:05，Ella 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xiaolongyuan** [comment]
+1

**Comment by ianwith** [comment]
热更新是有我们自己实现的一套部署上线流程来完成

**Comment by guoshao-dev** [comment]
可以稍微解释一下。这个还是挺简单的。
主要是提供一个 route.json 路由表即可。 
一个例子：

https://raw.githubusercontent.com/douban/rexxar-web/master/example/dist/routes.json

```
{
    "items": [{
        "remote_file": "https://raw.githubusercontent.com/douban/rexxar-web/master/example/dist/rexxar/demo-252452ae58.html",
        "deploy_time": "Sun, 09 Oct 2016 07:43:47 GMT",
        "uri": "douban://douban.com/rexxar_demo[/]?.*"
    }],
    "partial_items": [{
        "remote_file": "https://raw.githubusercontent.com/douban/rexxar-web/master/example/dist/rexxar/demo-252452ae58.html",
        "deploy_time": "Sun, 09 Oct 2016 07:43:47 GMT",
        "uri": "douban://partial.douban.com/rexxar_demo/_.*"
    }],
    "deploy_time": "Sun, 09 Oct 2016 07:43:47 GMT",
}
```

Rexxar-iOS 和 Rexxar-Android 两个客户端都有可以配置这个路由表的接口。如何将 route.json 中指示的 html，css，js 等静态资源打包和部署，这与每个开发者的开发环境强相关。所以，提供一个这样的 demo 也没有意义。
