### ISSUE TITLE
如果使用 vue 之类的前端框架做单页应用的话  路由应该怎么处理呢？

### ISSUE THREAD

**Issue by xiaolongyuan** [douban/rexxar-web#8]

**Comment by ianwith** [comment]
rexxar不规定你的具体实现框架的，对你的问题不是很明了，可以先看一下介绍
http://lincode.github.io/Rexxar-OpenSource

**Comment by xiaolongyuan** [comment]
单页应用状态下不管路径是什么 文件指向都是 index.html
例如以下路由：
- /login
- /register
- /user/1

最终文件指向都是 index.html

**Comment by xiaolongyuan** [comment]
https://github.com/douban/rexxar-android/issues/17
