### ISSUE TITLE
网络请求是如何进行的

### ISSUE THREAD

**Issue by xiaolongyuan** [douban/rexxar-web#9]
一般来说 一个网页发布几个版本？ h5一套  hybrid一套？ 

还是一个页面分不同环境进行？如果是这样的话，那么 网络请求:
- hybrid 环境下 是 native代理进行的 ？
- h5 环境下  如何？

不太明白 万求指导

**Comment by xiaolongyuan** [comment]
help

**Comment by ianwith** [comment]
页面根据不同环境分发到不同的使用场景

你提到的两点
1. rexxar本身有介绍，请查看[rexxar-ios](https://github.com/douban/rexxar-ios)、[rexxar-android](https://github.com/douban/rexxar-android)
2. 不同场景下可以使用API路径或许有所不同，根据服务器端的具体情况做不同的配置

**Comment by xiaolongyuan** [comment]
如果说 页面需要请求服务器上的api 该如何

例如 

```
          request.get({
            url: "http://192.168.199.78:8888/api/v1/activitys/list",
            params:{},
            success(){
              console.log("request ...........")
            },
            failure(){

            }
          })
```
这样拦截器并没有生效  查看源码 发现 代码只对特性协议host进行拦截  难道需要利用  'http://rexxar-container/api/' 进行一次中转？

变成这样：

```
http://rexxar-container/api/get?apiUrl=http://192.168.199.78:8888/api/v1/activitys/list 
```

还是说直接修改 源码 对 http://192.168.199.78:8888/api/v1/  也进行拦截？

**Comment by xiaolongyuan** [comment]
我查看的是Android对应 源码

```
 private boolean shouldIntercept(String requestUrl) {
        if (TextUtils.isEmpty(requestUrl)) {
            return false;
        }
        // file协议需要替换,用于html
        if (requestUrl.startsWith(Constants.FILE_AUTHORITY)) {
            return true;
        }

        // rexxar container api，需要拦截
        if (requestUrl.startsWith(Constants.CONTAINER_API_BASE)) {
            return true;
        }

        // 非合法uri，不拦截
        Uri uri = null;
        try {
            uri = Uri.parse(requestUrl);
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (null == uri) {
            return false;
        }

        // 非合法host，不拦截
        String host = uri.getHost();
        if (TextUtils.isEmpty(host)) {
            return false;
        }

        // 不能拦截的uri，不拦截
        Pattern pattern;
        Matcher matcher;
        for (String interceptHostItem : ResourceProxy.getInstance().getProxyHosts()) {
            pattern = Pattern.compile(interceptHostItem);
            matcher = pattern.matcher(host);
            if (matcher.find()) {
                return true;
            }
        }
        return false;
    }
```

**Comment by qluan** [comment]
@xiaolongyuan 
"如果说 页面需要请求服务器上的api 该如何"

可以分为3中情况，看自己的使用场景来用

1. 直接由web向服务器请求，不需要native包装一下请求；做法：api的host不在rexxar要拦截的host中即可，跟正常的网页请求一样
2. 要求native拦截包装一下请求再发向服务器，比如添加自定义参数；做法：这样就需要设置“特性协议host”
3. 把native当成服务器，请求native的数据，比如请求app的版本信息，这样可以 通过rexxar-container来做；

**Comment by xiaolongyuan** [comment]
明白了 原来还是要自己定制一下的。

那么 
第一种情况 应该是在h5环境中使用吧  这样的话 cookie状态是可以同步的。如果不是 直接向服务器请求的话 cookie等状态如何处理？

**Comment by xiaolongyuan** [comment]
第二种  做法是不是 例如 拦截 特定的 url  检验下是否是 api 请求 如果是则 添加cookie？

**Comment by xiaolongyuan** [comment]
关于第二种 ：
https://github.com/douban/rexxar-android/issues/23

似乎是把api 请求的域名添加成代理？

![image](https://cloud.githubusercontent.com/assets/3142363/24030682/36584f24-0b19-11e7-9c7f-b81f017db1c8.png)

那这里为啥只支持配置 host 而不是完成的路径？

**Comment by qluan** [comment]
@xiaolongyuan  
第二种拦截到请求后，允许不做任何修改直接返回，效果就跟第一种一样。  一般常做的修改也就是：添加access token，记录请求信息，不会影响到cookies原有逻辑。

第二种方式确实是针对域名配置的，希望native对请求的包装是针对一系列api的行为，而不是单个api。当然我们也支持只对单个api做包装修改，只需要在拦截到之后判断下path，不需要修改的直接返回就好。

就拿rexxar-android举例，AuthInterceptor是对特定域名的api添加auth信息，也可以只对特定path的请求添加。https://github.com/douban/rexxar-android/blob/master/sample/src/main/java/com/douban/rexxar/example/AuthInterceptor.java#L16

**Comment by xiaolongyuan** [comment]
我发现一个bug 开发时直接使用 url 加载访问 webpack进行热更新后 ：
使用库：axios (使用 rexxar 自带的 fetch一样)

问题 网络请求的数据没有返回给对应的webview
使用 chrome://inspect/#devices  发现检测到多个web

**Comment by xiaolongyuan** [comment]
我觉得还是针对 URL 进行拦截比较好 精准
特别是 当 缓存的资源和 API 是一个 HOST 那情景简直没法子测试  动不动  缓存资源失效（ webpack 热更新） 

另外就是 URI 方式 打开页面时 webpack 热更新后 常常有问题 打不开
